name: rftv3
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.16
  - pip=25.0
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.4
  - bzip2=1.0.8
  - ca-certificates
  - openssl=3.0.16
  - sqlite=3.45.3
  - ninja
  - pip:
    - accelerate
    - einops==0.8.1
    - flash-attn==2.5.5
    - numpy==1.26.4
    - transformers==4.51.3
    - triton==3.1.0
    - vllm==0.7.2
    - xformers==0.0.28.post3
    - tensorboardx
    - wandb
    - qwen-vl-utils 